version: '3'
services: 
    hugo:
        image: klakegg/hugo:ubuntu
        volumes:
            - ".:/src"
        entrypoint: ["hugo", "server", "--poll", "700ms"]
        ports:
            - "1313:1313"
        tty: true
        working_dir: /src